### ISSUE TITLE
Add a GUI

### ISSUE THREAD

**Issue by Mohamed-Ayaan358** [acmpesuecc/Doc-Scan#1]
### What do we want you to do?

Currently, we have to enter the file name, into the command line for us to compare the two files. Perhaps enter an upload tool where we can upload the files.

### Possible solutions

Anything is appreciated, as any improvements over the command line is quite nice :)

#### 1. Open Access time: 
 [30 minutes] if each block time has passed

 #### 2. Block time: 
[1 hour], to show significant progress.

 #### 3. Bounty points: 50 Points

 #### 4. Brownie points: 5-30 points based on the extent to which you have gone

**Comment by mayankpm** [comment]
@Mohamed-Ayaan358 can I please be assigned to work on this issue? Thanks

**Comment by Mohamed-Ayaan358** [comment]
> @Mohamed-Ayaan358 can I please be assigned to work on this issue? Thanks (Mayank PM)

Yes you can at @mayankpm

**Comment by Vaarun-Kamath** [comment]
Can i get this issue pls :) - VarunKamath PES2UG21CS594

**Comment by Mohamed-Ayaan358** [comment]
yes you can @Vaarun-Kamath

**Comment by Vaarun-Kamath** [comment]
so i have been assigned to this right?

**Comment by Mohamed-Ayaan358** [comment]
@Vaarun-Kamath @mayankpm I expect a significant update from either one of you, in the next 30 minutes for one of you to get selected for the block time. Where we will be forced to choose only one of your PRs based on who showed significant changes in this time period.

**Comment by Mohamed-Ayaan358** [comment]
> so i have been assigned to this right?

Since both of you did it before Free access was done, ill make an exception and either one of you should give me enough proof to go ahead with this issue. @Vaarun-Kamath @mayankpm

**Comment by samarth777** [comment]
can you assign this to me?

**Comment by Mohamed-Ayaan358** [comment]
@samarth777 Yes do note that you must make a significant contribution on top of the new merge.

**Comment by SarthakSKumar** [comment]
Can I work on this issue? I will implement a GUI using Tkinter for the same. I suppose the blocking time for the previous assignee is up! Thanks in advance

**Comment by SarthakSKumar** [comment]
I am working on it. Will update soon

**Comment by siddarthpai** [comment]
can i work on this

**Comment by Ganther3301** [comment]
hey @Mohamed-Ayaan358  can i work on this?
